---
- hosts: "centos7"
  become: "true"

  vars:
  -  USERNAME: GANESH
  -  SERVICENAME: "Apache-HTTPD From CenOS7"
  -  SERVERVERSION: "Apache HTTPD 2.0.8 on CenOS 7"

  tasks:
  - name: "Copy a sample html file to httpd web server location"
    template: src=index.html dest=/var/www/html/index.html

  - name: "Create a file and update the user and file permissions"
    file: path=/var/www/html/login.html state=touch owner=vagrant group=vagrant mode=0775
    notify: Restart httpd
  
  handlers:
  - name: Restart httpd 
    service: name=httpd state=restarted
