---
- hosts: "centos7"
  become: "true"

  vars:
  -  USERNAME: GANESH
  -  SERVICENAME: "Apache-HTTPD From CenOS7"
  -  SERVERVERSION: "Apache HTTPD 2.0.8 on CenOS 7"

  tasks:
  - name: "Install libselinux-python"
    yum: name=libselinux-python state=present

  - name: "Disable SE Linux"
    selinux: state=disabled

  - name: "Install apache http"
    yum: name=httpd state=present

  - name: "Make sure the apache has started "
    service: name=httpd state=started enabled=yes

  - name: "Enable tcp 80 port open in firewall"
    firewalld: port="80/tcp" permanent=yes state=enabled

  - name: "Restart the firewalld service"
    service: name=firewalld state=restarted

  - name: "Install curl command"
    yum: name=curl state=present

  - name: "Check if the curl command is working or not"
    shell: curl ipinfo.io/ip
    register: curl_output
  
  - debug: var=curl_output.stdout_lines

  - name: "Copy a sample html file to httpd web server location"
    template: src=index.html dest=/var/www/html/index.html

  - name: "Create a file and update the user and file permissions"
    file: path=/var/www/html/login.html state=touch owner=vagrant group=vagrant mode=0775
    notify: Restart httpd
  
  handlers:
  - name: Restart httpd 
    service: name=httpd state=restarted
